#!/bin/bash

curl --verbose http://secim-api.adilsecim.net/2/city/1.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-1.json
curl --verbose http://secim-api.adilsecim.net/2/city/2.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-2.json
curl --verbose http://secim-api.adilsecim.net/2/city/3.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-3.json
curl --verbose http://secim-api.adilsecim.net/2/city/4.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-4.json
curl --verbose http://secim-api.adilsecim.net/2/city/5.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-5.json
curl --verbose http://secim-api.adilsecim.net/2/city/6.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-6.json
curl --verbose http://secim-api.adilsecim.net/2/city/7.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-7.json
curl --verbose http://secim-api.adilsecim.net/2/city/8.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-8.json
curl --verbose http://secim-api.adilsecim.net/2/city/9.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-9.json
curl --verbose http://secim-api.adilsecim.net/2/city/10.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-10.json
curl --verbose http://secim-api.adilsecim.net/2/city/11.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-11.json
curl --verbose http://secim-api.adilsecim.net/2/city/12.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-12.json
curl --verbose http://secim-api.adilsecim.net/2/city/13.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-13.json
curl --verbose http://secim-api.adilsecim.net/2/city/14.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-14.json
curl --verbose http://secim-api.adilsecim.net/2/city/15.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-15.json
curl --verbose http://secim-api.adilsecim.net/2/city/16.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-16.json
curl --verbose http://secim-api.adilsecim.net/2/city/17.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-17.json
curl --verbose http://secim-api.adilsecim.net/2/city/18.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-18.json
curl --verbose http://secim-api.adilsecim.net/2/city/19.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-19.json
curl --verbose http://secim-api.adilsecim.net/2/city/20.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-20.json
curl --verbose http://secim-api.adilsecim.net/2/city/21.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-21.json
curl --verbose http://secim-api.adilsecim.net/2/city/22.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-22.json
curl --verbose http://secim-api.adilsecim.net/2/city/23.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-23.json
curl --verbose http://secim-api.adilsecim.net/2/city/24.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-24.json
curl --verbose http://secim-api.adilsecim.net/2/city/25.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-25.json
curl --verbose http://secim-api.adilsecim.net/2/city/26.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-26.json
curl --verbose http://secim-api.adilsecim.net/2/city/27.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-27.json
curl --verbose http://secim-api.adilsecim.net/2/city/28.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-28.json
curl --verbose http://secim-api.adilsecim.net/2/city/29.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-29.json
curl --verbose http://secim-api.adilsecim.net/2/city/30.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-30.json
curl --verbose http://secim-api.adilsecim.net/2/city/31.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-31.json
curl --verbose http://secim-api.adilsecim.net/2/city/32.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-32.json
curl --verbose http://secim-api.adilsecim.net/2/city/33.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-33.json
curl --verbose http://secim-api.adilsecim.net/2/city/34.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-34.json
curl --verbose http://secim-api.adilsecim.net/2/city/35.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-35.json
curl --verbose http://secim-api.adilsecim.net/2/city/36.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-36.json
curl --verbose http://secim-api.adilsecim.net/2/city/37.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-37.json
curl --verbose http://secim-api.adilsecim.net/2/city/38.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-38.json
curl --verbose http://secim-api.adilsecim.net/2/city/39.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-39.json
curl --verbose http://secim-api.adilsecim.net/2/city/40.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-40.json
curl --verbose http://secim-api.adilsecim.net/2/city/41.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-41.json
curl --verbose http://secim-api.adilsecim.net/2/city/42.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-42.json
curl --verbose http://secim-api.adilsecim.net/2/city/43.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-43.json
curl --verbose http://secim-api.adilsecim.net/2/city/44.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-44.json
curl --verbose http://secim-api.adilsecim.net/2/city/45.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-45.json
curl --verbose http://secim-api.adilsecim.net/2/city/46.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-46.json
curl --verbose http://secim-api.adilsecim.net/2/city/47.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-47.json
curl --verbose http://secim-api.adilsecim.net/2/city/48.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-48.json
curl --verbose http://secim-api.adilsecim.net/2/city/49.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-49.json
curl --verbose http://secim-api.adilsecim.net/2/city/50.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-50.json
curl --verbose http://secim-api.adilsecim.net/2/city/51.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-51.json
curl --verbose http://secim-api.adilsecim.net/2/city/52.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-52.json
curl --verbose http://secim-api.adilsecim.net/2/city/53.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-53.json
curl --verbose http://secim-api.adilsecim.net/2/city/54.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-54.json
curl --verbose http://secim-api.adilsecim.net/2/city/55.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-55.json
curl --verbose http://secim-api.adilsecim.net/2/city/56.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-56.json
curl --verbose http://secim-api.adilsecim.net/2/city/57.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-57.json
curl --verbose http://secim-api.adilsecim.net/2/city/58.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-58.json
curl --verbose http://secim-api.adilsecim.net/2/city/59.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-59.json
curl --verbose http://secim-api.adilsecim.net/2/city/60.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-60.json
curl --verbose http://secim-api.adilsecim.net/2/city/61.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-61.json
curl --verbose http://secim-api.adilsecim.net/2/city/62.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-62.json
curl --verbose http://secim-api.adilsecim.net/2/city/63.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-63.json
curl --verbose http://secim-api.adilsecim.net/2/city/64.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-64.json
curl --verbose http://secim-api.adilsecim.net/2/city/65.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-65.json
curl --verbose http://secim-api.adilsecim.net/2/city/66.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-66.json
curl --verbose http://secim-api.adilsecim.net/2/city/67.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-67.json
curl --verbose http://secim-api.adilsecim.net/2/city/68.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-68.json
curl --verbose http://secim-api.adilsecim.net/2/city/69.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-69.json
curl --verbose http://secim-api.adilsecim.net/2/city/70.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-70.json
curl --verbose http://secim-api.adilsecim.net/2/city/71.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-71.json
curl --verbose http://secim-api.adilsecim.net/2/city/72.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-72.json
curl --verbose http://secim-api.adilsecim.net/2/city/73.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-73.json
curl --verbose http://secim-api.adilsecim.net/2/city/74.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-74.json
curl --verbose http://secim-api.adilsecim.net/2/city/75.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-75.json
curl --verbose http://secim-api.adilsecim.net/2/city/76.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-76.json
curl --verbose http://secim-api.adilsecim.net/2/city/77.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-77.json
curl --verbose http://secim-api.adilsecim.net/2/city/78.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-78.json
curl --verbose http://secim-api.adilsecim.net/2/city/79.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-79.json
curl --verbose http://secim-api.adilsecim.net/2/city/80.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-80.json
curl --verbose http://secim-api.adilsecim.net/2/city/81.json --output veriler/cumhurbaskanligi-iller/secim-cumhurbaskanligi-il-81.json