#!/bin/bash

curl --verbose http://secim-api.adilsecim.net/1/city/1.json --output veriler/genel-iller/secim-genel-il-1.json
curl --verbose http://secim-api.adilsecim.net/1/city/2.json --output veriler/genel-iller/secim-genel-il-2.json
curl --verbose http://secim-api.adilsecim.net/1/city/3.json --output veriler/genel-iller/secim-genel-il-3.json
curl --verbose http://secim-api.adilsecim.net/1/city/4.json --output veriler/genel-iller/secim-genel-il-4.json
curl --verbose http://secim-api.adilsecim.net/1/city/5.json --output veriler/genel-iller/secim-genel-il-5.json
curl --verbose http://secim-api.adilsecim.net/1/city/6.json --output veriler/genel-iller/secim-genel-il-6.json
curl --verbose http://secim-api.adilsecim.net/1/city/7.json --output veriler/genel-iller/secim-genel-il-7.json
curl --verbose http://secim-api.adilsecim.net/1/city/8.json --output veriler/genel-iller/secim-genel-il-8.json
curl --verbose http://secim-api.adilsecim.net/1/city/9.json --output veriler/genel-iller/secim-genel-il-9.json
curl --verbose http://secim-api.adilsecim.net/1/city/10.json --output veriler/genel-iller/secim-genel-il-10.json
curl --verbose http://secim-api.adilsecim.net/1/city/11.json --output veriler/genel-iller/secim-genel-il-11.json
curl --verbose http://secim-api.adilsecim.net/1/city/12.json --output veriler/genel-iller/secim-genel-il-12.json
curl --verbose http://secim-api.adilsecim.net/1/city/13.json --output veriler/genel-iller/secim-genel-il-13.json
curl --verbose http://secim-api.adilsecim.net/1/city/14.json --output veriler/genel-iller/secim-genel-il-14.json
curl --verbose http://secim-api.adilsecim.net/1/city/15.json --output veriler/genel-iller/secim-genel-il-15.json
curl --verbose http://secim-api.adilsecim.net/1/city/16.json --output veriler/genel-iller/secim-genel-il-16.json
curl --verbose http://secim-api.adilsecim.net/1/city/17.json --output veriler/genel-iller/secim-genel-il-17.json
curl --verbose http://secim-api.adilsecim.net/1/city/18.json --output veriler/genel-iller/secim-genel-il-18.json
curl --verbose http://secim-api.adilsecim.net/1/city/19.json --output veriler/genel-iller/secim-genel-il-19.json
curl --verbose http://secim-api.adilsecim.net/1/city/20.json --output veriler/genel-iller/secim-genel-il-20.json
curl --verbose http://secim-api.adilsecim.net/1/city/21.json --output veriler/genel-iller/secim-genel-il-21.json
curl --verbose http://secim-api.adilsecim.net/1/city/22.json --output veriler/genel-iller/secim-genel-il-22.json
curl --verbose http://secim-api.adilsecim.net/1/city/23.json --output veriler/genel-iller/secim-genel-il-23.json
curl --verbose http://secim-api.adilsecim.net/1/city/24.json --output veriler/genel-iller/secim-genel-il-24.json
curl --verbose http://secim-api.adilsecim.net/1/city/25.json --output veriler/genel-iller/secim-genel-il-25.json
curl --verbose http://secim-api.adilsecim.net/1/city/26.json --output veriler/genel-iller/secim-genel-il-26.json
curl --verbose http://secim-api.adilsecim.net/1/city/27.json --output veriler/genel-iller/secim-genel-il-27.json
curl --verbose http://secim-api.adilsecim.net/1/city/28.json --output veriler/genel-iller/secim-genel-il-28.json
curl --verbose http://secim-api.adilsecim.net/1/city/29.json --output veriler/genel-iller/secim-genel-il-29.json
curl --verbose http://secim-api.adilsecim.net/1/city/30.json --output veriler/genel-iller/secim-genel-il-30.json
curl --verbose http://secim-api.adilsecim.net/1/city/31.json --output veriler/genel-iller/secim-genel-il-31.json
curl --verbose http://secim-api.adilsecim.net/1/city/32.json --output veriler/genel-iller/secim-genel-il-32.json
curl --verbose http://secim-api.adilsecim.net/1/city/33.json --output veriler/genel-iller/secim-genel-il-33.json
curl --verbose http://secim-api.adilsecim.net/1/city/34.json --output veriler/genel-iller/secim-genel-il-34.json
curl --verbose http://secim-api.adilsecim.net/1/city/35.json --output veriler/genel-iller/secim-genel-il-35.json
curl --verbose http://secim-api.adilsecim.net/1/city/36.json --output veriler/genel-iller/secim-genel-il-36.json
curl --verbose http://secim-api.adilsecim.net/1/city/37.json --output veriler/genel-iller/secim-genel-il-37.json
curl --verbose http://secim-api.adilsecim.net/1/city/38.json --output veriler/genel-iller/secim-genel-il-38.json
curl --verbose http://secim-api.adilsecim.net/1/city/39.json --output veriler/genel-iller/secim-genel-il-39.json
curl --verbose http://secim-api.adilsecim.net/1/city/40.json --output veriler/genel-iller/secim-genel-il-40.json
curl --verbose http://secim-api.adilsecim.net/1/city/41.json --output veriler/genel-iller/secim-genel-il-41.json
curl --verbose http://secim-api.adilsecim.net/1/city/42.json --output veriler/genel-iller/secim-genel-il-42.json
curl --verbose http://secim-api.adilsecim.net/1/city/43.json --output veriler/genel-iller/secim-genel-il-43.json
curl --verbose http://secim-api.adilsecim.net/1/city/44.json --output veriler/genel-iller/secim-genel-il-44.json
curl --verbose http://secim-api.adilsecim.net/1/city/45.json --output veriler/genel-iller/secim-genel-il-45.json
curl --verbose http://secim-api.adilsecim.net/1/city/46.json --output veriler/genel-iller/secim-genel-il-46.json
curl --verbose http://secim-api.adilsecim.net/1/city/47.json --output veriler/genel-iller/secim-genel-il-47.json
curl --verbose http://secim-api.adilsecim.net/1/city/48.json --output veriler/genel-iller/secim-genel-il-48.json
curl --verbose http://secim-api.adilsecim.net/1/city/49.json --output veriler/genel-iller/secim-genel-il-49.json
curl --verbose http://secim-api.adilsecim.net/1/city/50.json --output veriler/genel-iller/secim-genel-il-50.json
curl --verbose http://secim-api.adilsecim.net/1/city/51.json --output veriler/genel-iller/secim-genel-il-51.json
curl --verbose http://secim-api.adilsecim.net/1/city/52.json --output veriler/genel-iller/secim-genel-il-52.json
curl --verbose http://secim-api.adilsecim.net/1/city/53.json --output veriler/genel-iller/secim-genel-il-53.json
curl --verbose http://secim-api.adilsecim.net/1/city/54.json --output veriler/genel-iller/secim-genel-il-54.json
curl --verbose http://secim-api.adilsecim.net/1/city/55.json --output veriler/genel-iller/secim-genel-il-55.json
curl --verbose http://secim-api.adilsecim.net/1/city/56.json --output veriler/genel-iller/secim-genel-il-56.json
curl --verbose http://secim-api.adilsecim.net/1/city/57.json --output veriler/genel-iller/secim-genel-il-57.json
curl --verbose http://secim-api.adilsecim.net/1/city/58.json --output veriler/genel-iller/secim-genel-il-58.json
curl --verbose http://secim-api.adilsecim.net/1/city/59.json --output veriler/genel-iller/secim-genel-il-59.json
curl --verbose http://secim-api.adilsecim.net/1/city/60.json --output veriler/genel-iller/secim-genel-il-60.json
curl --verbose http://secim-api.adilsecim.net/1/city/61.json --output veriler/genel-iller/secim-genel-il-61.json
curl --verbose http://secim-api.adilsecim.net/1/city/62.json --output veriler/genel-iller/secim-genel-il-62.json
curl --verbose http://secim-api.adilsecim.net/1/city/63.json --output veriler/genel-iller/secim-genel-il-63.json
curl --verbose http://secim-api.adilsecim.net/1/city/64.json --output veriler/genel-iller/secim-genel-il-64.json
curl --verbose http://secim-api.adilsecim.net/1/city/65.json --output veriler/genel-iller/secim-genel-il-65.json
curl --verbose http://secim-api.adilsecim.net/1/city/66.json --output veriler/genel-iller/secim-genel-il-66.json
curl --verbose http://secim-api.adilsecim.net/1/city/67.json --output veriler/genel-iller/secim-genel-il-67.json
curl --verbose http://secim-api.adilsecim.net/1/city/68.json --output veriler/genel-iller/secim-genel-il-68.json
curl --verbose http://secim-api.adilsecim.net/1/city/69.json --output veriler/genel-iller/secim-genel-il-69.json
curl --verbose http://secim-api.adilsecim.net/1/city/70.json --output veriler/genel-iller/secim-genel-il-70.json
curl --verbose http://secim-api.adilsecim.net/1/city/71.json --output veriler/genel-iller/secim-genel-il-71.json
curl --verbose http://secim-api.adilsecim.net/1/city/72.json --output veriler/genel-iller/secim-genel-il-72.json
curl --verbose http://secim-api.adilsecim.net/1/city/73.json --output veriler/genel-iller/secim-genel-il-73.json
curl --verbose http://secim-api.adilsecim.net/1/city/74.json --output veriler/genel-iller/secim-genel-il-74.json
curl --verbose http://secim-api.adilsecim.net/1/city/75.json --output veriler/genel-iller/secim-genel-il-75.json
curl --verbose http://secim-api.adilsecim.net/1/city/76.json --output veriler/genel-iller/secim-genel-il-76.json
curl --verbose http://secim-api.adilsecim.net/1/city/77.json --output veriler/genel-iller/secim-genel-il-77.json
curl --verbose http://secim-api.adilsecim.net/1/city/78.json --output veriler/genel-iller/secim-genel-il-78.json
curl --verbose http://secim-api.adilsecim.net/1/city/79.json --output veriler/genel-iller/secim-genel-il-79.json
curl --verbose http://secim-api.adilsecim.net/1/city/80.json --output veriler/genel-iller/secim-genel-il-80.json
curl --verbose http://secim-api.adilsecim.net/1/city/81.json --output veriler/genel-iller/secim-genel-il-81.json